# Generated by Django 3.2.6 on 2022-03-05 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(blank=True, default=False, null=True)),
                ('role', models.CharField(blank=True, choices=[('Staff', 'Staff'), ('Others', 'Others')], max_length=20, null=True)),
                ('first_name', models.CharField(max_length=500, null=True)),
                ('middle_name', models.CharField(max_length=500, null=True)),
                ('last_name', models.CharField(max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, default='defaulf-user.png', upload_to='prof/photos')),
                ('company_photo', models.ImageField(blank=True, default='defaulf-user.png', upload_to='company/photos')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
