# Generated by Django 3.2.6 on 2022-03-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20220318_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='planned_maintenace',
            new_name='planned_maintenance',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='preventive_maintenace',
            new_name='preventive_maintenance',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='routine_maintenace',
            new_name='routine_maintenance',
        ),
    ]
