# Generated by Django 3.2.6 on 2022-03-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20220318_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='approraited_budget',
        ),
    ]
