# Generated by Django 3.2.6 on 2022-03-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_remove_budget_approraited_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
