# Generated by Django 3.2.6 on 2022-03-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_remove_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategic_plan', models.CharField(max_length=500, null=True)),
                ('management_plan', models.CharField(max_length=500, null=True)),
                ('business_plan', models.CharField(max_length=500, null=True)),
                ('department_plan', models.CharField(max_length=500, null=True)),
                ('agency_plan', models.CharField(max_length=500, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NonRoadAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=500, null=True)),
                ('laboratories', models.IntegerField(null=True)),
                ('facilities', models.CharField(max_length=500, null=True)),
                ('plant_equipment', models.IntegerField(null=True)),
                ('asphalt_plant', models.IntegerField(null=True)),
                ('graders', models.IntegerField(null=True)),
                ('sundry_equipment', models.IntegerField(null=True)),
                ('mini_asphalt', models.IntegerField(null=True)),
                ('loader', models.IntegerField(null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PBMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintained_road', models.IntegerField(null=True)),
                ('road_length', models.IntegerField(null=True)),
                ('cost_of_road', models.IntegerField(null=True)),
                ('capacity_of_contractor', models.CharField(max_length=500, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PESTLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('political', models.CharField(max_length=500, null=True)),
                ('economic', models.CharField(max_length=500, null=True)),
                ('social', models.CharField(max_length=500, null=True)),
                ('technology', models.CharField(max_length=500, null=True)),
                ('legal', models.CharField(max_length=500, null=True)),
                ('environment', models.CharField(max_length=500, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicPrivatePartnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legislative_for_ppp', models.CharField(max_length=500, null=True)),
                ('dedicated_ppp', models.BooleanField(default=False, null=True)),
                ('dedicated_ppp_ministry', models.CharField(max_length=500, null=True)),
                ('no_ppp_road', models.IntegerField(null=True)),
                ('length_ppp_road', models.IntegerField(null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('numbers', models.IntegerField(null=True)),
                ('classes', models.CharField(max_length=500, null=True)),
                ('value', models.IntegerField(null=True)),
                ('rebuilding_cost', models.IntegerField(null=True)),
                ('road_furniture_cost', models.IntegerField(null=True)),
                ('roads', models.CharField(max_length=500, null=True)),
                ('bridges', models.CharField(max_length=500, null=True)),
                ('tolled', models.BooleanField(default=False, null=True)),
                ('consession', models.BooleanField(default=False, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadInformantion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_source', models.CharField(max_length=500, null=True)),
                ('periodic_audit', models.BooleanField(default=False, null=True)),
                ('external_audit', models.BooleanField(default=False, null=True)),
                ('tolled_road', models.IntegerField(null=True)),
                ('total_length_road_corridor', models.IntegerField(null=True)),
                ('corridor_condition', models.CharField(max_length=500, null=True)),
                ('secondary_road_lenght', models.IntegerField(null=True)),
                ('secondary_road_propotion', models.CharField(max_length=500, null=True)),
                ('unpaved_road_lenght', models.IntegerField(null=True)),
                ('unpaved_road_condition', models.CharField(max_length=500, null=True)),
                ('no_road_per_state', models.IntegerField(null=True)),
                ('no_road_per_zone', models.IntegerField(null=True)),
                ('total_length_per_state', models.IntegerField(null=True)),
                ('total_length_per_zone', models.IntegerField(null=True)),
                ('condition_federal_road', models.CharField(max_length=500, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadMaintenanceImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_plan', models.CharField(max_length=500, null=True)),
                ('gdp_economy', models.CharField(max_length=500, null=True)),
                ('climate_change', models.CharField(max_length=500, null=True)),
                ('other_factors_1', models.CharField(max_length=500, null=True)),
                ('other_factors_2', models.CharField(max_length=500, null=True)),
                ('other_factors_3', models.CharField(max_length=500, null=True)),
                ('other_factors_4', models.CharField(max_length=500, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('stake', models.CharField(max_length=500, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('phone', models.CharField(max_length=500, null=True)),
                ('survey', models.CharField(max_length=500, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
