# Generated by Django 3.2.6 on 2022-03-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_managementplan_nonroadasset_pbmc_pestle_publicprivatepartnership_roadasset_roadinformantion_roadmain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmaintenanceimpact',
            name='other_factors_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='roadmaintenanceimpact',
            name='other_factors_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='roadmaintenanceimpact',
            name='other_factors_3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='roadmaintenanceimpact',
            name='other_factors_4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
