# Generated by Django 3.2.6 on 2022-03-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_auto_20220321_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonroadasset',
            name='plant_equipment',
        ),
    ]
