# Generated by Django 3.2.6 on 2022-03-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_remove_nonroadasset_plant_equipment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoadInformantion',
            new_name='RoadInformation',
        ),
    ]
