# Generated by Django 3.2.6 on 2022-03-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_inventoryroad_legend_nonroadproject_projectmaintenancework_roadproject_workstream'),
    ]

    operations = [
        migrations.AddField(
            model_name='legend',
            name='bc',
            field=models.IntegerField(null=True),
        ),
    ]
