# Generated by Django 3.2.6 on 2022-03-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_legend_bc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=500, null=True)),
                ('contractor_no', models.IntegerField(null=True)),
                ('contract_sum', models.IntegerField(null=True)),
                ('length_recovered_1', models.IntegerField(null=True)),
                ('length_recovered_2', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=500, null=True)),
                ('kpi', models.CharField(max_length=500, null=True)),
                ('baseline', models.IntegerField(null=True)),
                ('target', models.IntegerField(null=True)),
                ('achievement', models.IntegerField(null=True)),
                ('financial', models.IntegerField(null=True)),
                ('challenges', models.TextField(null=True)),
                ('job_created', models.CharField(max_length=500, null=True)),
                ('no_contractor', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryMaintenace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=500, null=True)),
                ('name', models.CharField(max_length=500, null=True)),
                ('project_id', models.CharField(max_length=500, null=True)),
                ('contractor_name', models.CharField(max_length=500, null=True)),
                ('date_award', models.DateField(null=True)),
                ('date_commence', models.DateField(null=True)),
                ('date_complete', models.DateField(null=True)),
                ('contract_sum', models.IntegerField(null=True)),
                ('compl', models.IntegerField(null=True)),
                ('length_recovered', models.IntegerField(null=True)),
                ('job_created', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
