# Generated by Django 3.2.6 on 2022-03-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0013_activities_kpi_summarymaintenace'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SummaryMaintenace',
            new_name='SummaryMaintenance',
        ),
    ]
