# Generated by Django 3.2.6 on 2022-03-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0014_rename_summarymaintenace_summarymaintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='achievement',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='baseline',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='financial',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='job_created',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='target',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
