# Generated by Django 3.2.6 on 2022-03-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0016_alter_summarymaintenance_compl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverables1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable_no', models.CharField(max_length=1500, null=True)),
                ('description', models.CharField(max_length=1500, null=True)),
                ('support', models.CharField(max_length=500, null=True)),
                ('main_output', models.CharField(max_length=500, null=True)),
                ('baseline', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('target', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('actual', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('perf', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('q1_target', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('q1_actual', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('q1_perf', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('q2_target', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('q2_actual', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('q2_perf', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('q3_target', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('q3_actual', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('q3_perf', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('annual_target_1', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('annual_target_2', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('annual_target_3', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('challenges', models.TextField(null=True)),
                ('recommendations', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deliverables2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable_no', models.CharField(max_length=1500, null=True)),
                ('year', models.CharField(max_length=500, null=True)),
                ('description', models.CharField(max_length=1500, null=True)),
                ('types', models.CharField(max_length=500, null=True)),
                ('main_output', models.CharField(max_length=500, null=True)),
                ('metric', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('baseline', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('target', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('actual', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('q1_target', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('q1_actual', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('q2_target', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('q2_actual', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('q3_target', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('q3_actual', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('q4_target', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('q4_actual', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('annual_target_1', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('annual_target_2', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('annual_target_3', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('source_data', models.TextField(null=True)),
                ('agency', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.CharField(max_length=500, null=True)),
                ('y_2020', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('q1_2021', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('q2_2021', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('q3_2021', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
