# Generated by Django 3.2.6 on 2022-03-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0017_deliverables1_deliverables2_summaryscorecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverables1',
            name='year',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
