# Generated by Django 3.2.6 on 2022-03-25 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0019_auto_20220325_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverables2',
            old_name='annual_target_1',
            new_name='annual_actual',
        ),
        migrations.RenameField(
            model_name='deliverables2',
            old_name='annual_target_2',
            new_name='annual_target',
        ),
        migrations.RemoveField(
            model_name='deliverables2',
            name='annual_target_3',
        ),
    ]
