# Generated by Django 3.2.6 on 2022-03-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0022_auto_20220325_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
    ]
