# Generated by Django 3.2.6 on 2022-03-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0024_alter_folderfile_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateMaintenanceCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, choices=[('Periodic', 'Periodic'), ('Routine', 'Routine')], max_length=20, null=True)),
                ('dual_carriage_amount', models.IntegerField(null=True)),
                ('dual_carriage_percent', models.IntegerField(null=True)),
                ('single_carriage_amount', models.IntegerField(null=True)),
                ('single_carriage_percent', models.IntegerField(null=True)),
                ('earth_carriage_amount', models.IntegerField(null=True)),
                ('earth_carriage_percent', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrbanMaintenanceCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, choices=[('Periodic', 'Periodic'), ('Routine', 'Routine')], max_length=20, null=True)),
                ('dual_carriage_amount', models.IntegerField(null=True)),
                ('dual_carriage_percent', models.IntegerField(null=True)),
                ('single_carriage_amount', models.IntegerField(null=True)),
                ('single_carriage_percent', models.IntegerField(null=True)),
                ('earth_carriage_amount', models.IntegerField(null=True)),
                ('earth_carriage_percent', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='MaintenanceCost',
            new_name='FederalMaintenanceCost',
        ),
    ]
