# Generated by Django 3.2.6 on 2022-03-25 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0025_auto_20220325_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='federalmaintenancecost',
            name='level',
        ),
    ]
