# Generated by Django 3.2.6 on 2022-04-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0030_pbmc_road'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
