# Generated by Django 3.2.6 on 2022-04-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0032_auto_20220401_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadasset',
            name='bridges',
        ),
        migrations.RemoveField(
            model_name='roadasset',
            name='consession',
        ),
        migrations.RemoveField(
            model_name='roadasset',
            name='rebuilding_cost',
        ),
        migrations.RemoveField(
            model_name='roadasset',
            name='road_furniture_cost',
        ),
        migrations.RemoveField(
            model_name='roadasset',
            name='roads',
        ),
        migrations.RemoveField(
            model_name='roadasset',
            name='tolled',
        ),
        migrations.AddField(
            model_name='roadasset',
            name='asset',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
