# Generated by Django 3.2.6 on 2022-04-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0033_auto_20220401_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='other',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
