# Generated by Django 3.2.6 on 2022-04-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0040_importfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonroadasset',
            name='asphalt_plant',
        ),
        migrations.RemoveField(
            model_name='nonroadasset',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='nonroadasset',
            name='graders',
        ),
        migrations.RemoveField(
            model_name='nonroadasset',
            name='laboratories',
        ),
        migrations.RemoveField(
            model_name='nonroadasset',
            name='loader',
        ),
        migrations.RemoveField(
            model_name='nonroadasset',
            name='mini_asphalt',
        ),
        migrations.RemoveField(
            model_name='nonroadasset',
            name='sundry_equipment',
        ),
        migrations.AddField(
            model_name='nonroadasset',
            name='asset',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='nonroadasset',
            name='classes',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='nonroadasset',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='nonroadasset',
            name='numbers',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nonroadasset',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
