# Generated by Django 3.2.6 on 2022-05-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0041_auto_20220412_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmaintenancework',
            old_name='mda',
            new_name='project',
        ),
        migrations.AddField(
            model_name='projectmaintenancework',
            name='year',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
