# Generated by Django 3.2.6 on 2022-05-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0042_auto_20220510_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadproject',
            name='diralables',
        ),
        migrations.AddField(
            model_name='roadproject',
            name='year',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='roadproject',
            name='east_west',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='roadproject',
            name='engineering',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
