# Generated by Django 3.2.6 on 2022-05-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0044_rename_engineering_roadproject_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonroadproject',
            name='year',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
