# Generated by Django 3.2.6 on 2022-05-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0045_nonroadproject_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='federalmaintenancecost',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ruralmaintenancecost',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statemaintenancecost',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='urbanmaintenancecost',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='villagemaintenancecost',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='federalmaintenancecost',
            name='mode',
            field=models.CharField(blank=True, choices=[('Periodic', 'Periodic'), ('Routine', 'Routine'), ('Corrective', 'Corrective'), ('Reactive', 'Reactive'), ('Emergency', 'Emergency')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nonroadproject',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='projectmaintenancework',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='roadproject',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ruralmaintenancecost',
            name='mode',
            field=models.CharField(blank=True, choices=[('Periodic', 'Periodic'), ('Routine', 'Routine'), ('Corrective', 'Corrective'), ('Reactive', 'Reactive'), ('Emergency', 'Emergency')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='statemaintenancecost',
            name='mode',
            field=models.CharField(blank=True, choices=[('Periodic', 'Periodic'), ('Routine', 'Routine'), ('Corrective', 'Corrective'), ('Reactive', 'Reactive'), ('Emergency', 'Emergency')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='urbanmaintenancecost',
            name='mode',
            field=models.CharField(blank=True, choices=[('Periodic', 'Periodic'), ('Routine', 'Routine'), ('Corrective', 'Corrective'), ('Reactive', 'Reactive'), ('Emergency', 'Emergency')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='villagemaintenancecost',
            name='mode',
            field=models.CharField(blank=True, choices=[('Periodic', 'Periodic'), ('Routine', 'Routine'), ('Corrective', 'Corrective'), ('Reactive', 'Reactive'), ('Emergency', 'Emergency')], max_length=20, null=True),
        ),
    ]
