# Generated by Django 3.2.6 on 2022-05-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0046_auto_20220510_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryroad',
            name='bc',
        ),
        migrations.RemoveField(
            model_name='inventoryroad',
            name='wc',
        ),
        migrations.AddField(
            model_name='inventoryroad',
            name='ac',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inventoryroad',
            name='total_carriageway',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
