# Generated by Django 3.2.6 on 2022-05-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0047_auto_20220510_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legend',
            name='bc',
        ),
        migrations.RemoveField(
            model_name='legend',
            name='wc',
        ),
        migrations.AlterField(
            model_name='legend',
            name='asphaltic_concrete',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
