# Generated by Django 3.2.6 on 2022-05-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0049_auto_20220510_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryscorecard',
            name='length_recovered',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
