# Generated by Django 3.2.6 on 2022-05-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0050_summaryscorecard_length_recovered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstream',
            name='bad',
        ),
        migrations.RemoveField(
            model_name='workstream',
            name='fair',
        ),
        migrations.RemoveField(
            model_name='workstream',
            name='good',
        ),
        migrations.RemoveField(
            model_name='workstream',
            name='poor',
        ),
        migrations.AddField(
            model_name='workstream',
            name='ball_unit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workstream',
            name='condition',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workstream',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workstream',
            name='road',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workstream',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workstream',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
