# Generated by Django 3.2.6 on 2022-05-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0051_auto_20220510_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('fund', models.CharField(max_length=500, null=True)),
                ('road_user', models.CharField(max_length=500, null=True)),
                ('public_private', models.CharField(max_length=500, null=True)),
                ('road_agency', models.CharField(max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
