# Generated by Django 3.2.6 on 2022-05-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0054_auto_20220516_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='media_folder',
            field=models.CharField(blank=True, choices=[('Project', 'Project'), ('Cost', 'Cost'), ('Inventory', 'Inventory'), ('Performance', 'Performance'), ('Scorecard', 'Scorecard'), ('External', 'External'), ('Media', 'Media')], max_length=500, null=True),
        ),
    ]
